/*
 * Catalogue PHONE 229.
 *
 * Pour ajouter un produit : copier un bloc { ... }, changer l'id (unique, sans espaces)
 * et les informations. Pour mettre une vraie photo : placer le fichier dans le dossier
 * images/ puis renseigner image: "images/nom-du-fichier.jpg".
 * Sans photo, un visuel provisoire est dessiné automatiquement avec la couleur "teinte".
 *
 * categorie : "Téléphone", "Tablette", "Ordinateur" ou "Accessoire"
 * etat      : "Neuf", "Reconditionné" ou "Occasion"
 * vedette   : true pour l'afficher sur la page d'accueil
 */
const PRODUITS = [
  {
    id: "iphone-15-pro-max",
    nom: "iPhone 15 Pro Max",
    marque: "Apple",
    categorie: "Téléphone",
    prix: 850000,
    stockage: "256 Go",
    ram: "8 Go",
    etat: "Neuf",
    teinte: "#6B6E73",
    image: "",
    vedette: true,
    description:
      "Le plus grand iPhone de la gamme 15, en titane. Idéal pour la photo, la vidéo et les journées chargées.",
    points: ["Écran 6,7 pouces Super Retina XDR", "Puce A17 Pro", "Triple caméra 48 Mpx", "Port USB-C"],
  },
  {
    id: "iphone-14",
    nom: "iPhone 14",
    marque: "Apple",
    categorie: "Téléphone",
    prix: 390000,
    stockage: "128 Go",
    ram: "6 Go",
    etat: "Reconditionné",
    teinte: "#5B4A7A",
    image: "",
    vedette: false,
    description:
      "Un iPhone récent à prix réduit. Batterie contrôlée et fonctions testées une à une en boutique.",
    points: ["Écran 6,1 pouces", "Puce A15 Bionic", "Double caméra 12 Mpx", "Batterie contrôlée"],
  },
  {
    id: "iphone-13",
    nom: "iPhone 13",
    marque: "Apple",
    categorie: "Téléphone",
    prix: 300000,
    stockage: "128 Go",
    ram: "4 Go",
    etat: "Occasion",
    teinte: "#2F5470",
    image: "",
    vedette: false,
    description: "L'entrée dans l'univers iPhone au meilleur prix. Testé, nettoyé et prêt à l'emploi.",
    points: ["Écran 6,1 pouces", "Puce A15 Bionic", "Face ID", "Double caméra 12 Mpx"],
  },
  {
    id: "galaxy-s24-ultra",
    nom: "Galaxy S24 Ultra",
    marque: "Samsung",
    categorie: "Téléphone",
    prix: 780000,
    stockage: "256 Go",
    ram: "12 Go",
    etat: "Neuf",
    teinte: "#3C3A38",
    image: "",
    vedette: true,
    description:
      "Le haut de gamme Samsung avec stylet S Pen intégré et zoom photo très puissant.",
    points: ["Écran 6,8 pouces 120 Hz", "Caméra 200 Mpx", "Stylet S Pen intégré", "Batterie 5 000 mAh"],
  },
  {
    id: "galaxy-a55",
    nom: "Galaxy A55 5G",
    marque: "Samsung",
    categorie: "Téléphone",
    prix: 245000,
    stockage: "128 Go",
    ram: "8 Go",
    etat: "Neuf",
    teinte: "#7C9CC4",
    image: "",
    vedette: true,
    description: "Le milieu de gamme solide : beau écran, bonne autonomie et compatible 5G.",
    points: ["Écran 6,6 pouces Super AMOLED", "Compatible 5G", "Caméra 50 Mpx", "Batterie 5 000 mAh"],
  },
  {
    id: "galaxy-a15",
    nom: "Galaxy A15",
    marque: "Samsung",
    categorie: "Téléphone",
    prix: 95000,
    stockage: "128 Go",
    ram: "4 Go",
    etat: "Neuf",
    teinte: "#2C3E50",
    image: "",
    vedette: false,
    description: "Le smartphone fiable pour tous les jours, à petit prix.",
    points: ["Écran 6,5 pouces", "Caméra 50 Mpx", "Batterie 5 000 mAh", "Double SIM"],
  },
  {
    id: "honor-magic6-lite",
    nom: "Honor Magic6 Lite",
    marque: "Honor",
    categorie: "Téléphone",
    prix: 175000,
    stockage: "256 Go",
    ram: "8 Go",
    etat: "Neuf",
    teinte: "#C46A3A",
    image: "",
    vedette: false,
    description: "Grand écran incurvé résistant aux chocs et autonomie de deux jours.",
    points: ["Écran 6,78 pouces incurvé", "Caméra 108 Mpx", "Batterie 5 300 mAh", "Charge rapide 35 W"],
  },
  {
    id: "honor-x8b",
    nom: "Honor X8b",
    marque: "Honor",
    categorie: "Téléphone",
    prix: 135000,
    stockage: "256 Go",
    ram: "8 Go",
    etat: "Neuf",
    teinte: "#4E7D6B",
    image: "",
    vedette: false,
    description: "Fin, léger et beaucoup de stockage pour le prix.",
    points: ["Écran 6,7 pouces AMOLED", "Caméra 108 Mpx", "256 Go de stockage", "Charge rapide 35 W"],
  },
  {
    id: "ipad-10",
    nom: "iPad 10e génération",
    marque: "Apple",
    categorie: "Tablette",
    prix: 290000,
    stockage: "64 Go",
    ram: "4 Go",
    etat: "Neuf",
    teinte: "#3F7FB0",
    image: "",
    vedette: true,
    description: "La tablette pour l'école, le travail et les films, avec un grand écran de 10,9 pouces.",
    points: ["Écran 10,9 pouces Liquid Retina", "Puce A14 Bionic", "Port USB-C", "Touch ID"],
  },
  {
    id: "macbook-air-m2",
    nom: "MacBook Air M2 13\"",
    marque: "Apple",
    categorie: "Ordinateur",
    prix: 650000,
    stockage: "256 Go SSD",
    ram: "8 Go",
    etat: "Reconditionné",
    teinte: "#8A8D91",
    image: "",
    vedette: false,
    description: "Ordinateur portable fin et silencieux, jusqu'à 18 heures d'autonomie.",
    points: ["Écran 13,6 pouces Liquid Retina", "Puce Apple M2", "Jusqu'à 18 h d'autonomie", "Clavier rétroéclairé"],
  },
  {
    id: "airpods-pro-2",
    nom: "AirPods Pro (2e génération)",
    marque: "Apple",
    categorie: "Accessoire",
    prix: 145000,
    stockage: "",
    ram: "",
    etat: "Neuf",
    teinte: "#B9BEC3",
    image: "",
    vedette: false,
    description: "Écouteurs sans fil avec réduction de bruit active et boîtier de charge USB-C.",
    points: ["Réduction de bruit active", "Mode Transparence", "Boîtier de charge USB-C", "Jusqu'à 6 h d'écoute"],
  },
  {
    id: "chargeur-samsung-25w",
    nom: "Chargeur rapide Samsung 25 W",
    marque: "Samsung",
    categorie: "Accessoire",
    prix: 12000,
    stockage: "",
    ram: "",
    etat: "Neuf",
    teinte: "#2B2B2B",
    image: "",
    vedette: false,
    description: "Chargeur d'origine Samsung avec câble USB-C, pour une charge rapide en toute sécurité.",
    points: ["Charge rapide 25 W", "Câble USB-C inclus", "Produit d'origine Samsung"],
  },
];
